somethingUpdatesInstall: UI: Robustness: Ensure that entered ignored package version matches the currently offered package
I've confused the regexp with a glob and entered 1\.17\.* instead of 1\.17\..*; that resulted in the available package not being ignored and re-offered, which took a lot of time to troubleshoot.
Check the extended regexp match against the currently offered package version and balk if it doesn't match.

FIX: Check for [ -n "$packageVersion" ] ineffective because of single quotes

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/somethingUpdatesInstall b/bin/somethingUpdatesInstall
--- a/bin/somethingUpdatesInstall
+++ b/bin/somethingUpdatesInstall
@@ -222,12 +222,22 @@ ignoreEnteredVersion()
     local packageName="${1:?}"; shift
     local packageVersion literalPackageVersion; packageVersion="$(getPackageVersion "$packageName")" \
 	&& literalPackageVersion="$(toLiteralRegexp --extended-regexp "$packageVersion")"
+    local offeredPackageVersion="$packageVersion"
 
-    packageVersion="$(userquery -p "$packageName version pattern (anchored extended regexp; .* for all versions): " -r -e -i "$literalPackageVersion")" \
-	&& [ -n '$packageVersion' ] \
-	&& addIgnorePattern "$packageName" --version "${packageVersion:?}" \
-	&& printf 'Put %s version-pattern %s onto the ignore list. Use $ %q --no-ignore %q⏎ to unignore.\n' "$packageName" "$packageVersion" "${SOMETHING_SUBJECT}-updates-available" "$packageName" \
-	&& status=0
+    while :
+    do
+	packageVersion="$(userquery -p "$packageName version pattern (anchored extended regexp; .* for all versions): " -r -e -i "$literalPackageVersion")" || return $?
+	[ -n "$packageVersion" ] || return 4
+	if [[ ! "$offeredPackageVersion" =~ ^${packageVersion}$ ]]; then
+	    printf >&2 'ERROR: Entered version pattern /%s/ does not match the currently offered version %s; please try again or clear the pattern to abort.\n' "$packageVersion" "$offeredPackageVersion"
+	    continue
+	fi
+
+	addIgnorePattern "$packageName" --version "${packageVersion:?}" \
+	    && printf 'Put %s version-pattern %s onto the ignore list. Use $ %q --no-ignore %q⏎ to unignore.\n' "$packageName" "$packageVersion" "${SOMETHING_SUBJECT}-updates-available" "$packageName" \
+	    && status=0
+	break
+    done
 }
 
 
