ENH: Use SOMETHING_SPECIAL_DEFINITIONS for update prerequisites
The client can specify a setup-software group definitions file, on which the current package name is looked up. If a corresponding definition exists and is not installed yet, the resulting command is immediately executed (and the package is only updated if that succeeds).
I've encountered some Python 3 packages that required some lib...-dev libraries (installed through the native package manager) to correctly compile. Through setup-software, we can handle any kind of prerequisite (native, Python, or custom), for great flexibility.

diff --git a/bin/somethingUpdatesInstall b/bin/somethingUpdatesInstall
--- a/bin/somethingUpdatesInstall
+++ b/bin/somethingUpdatesInstall
@@ -52,6 +52,10 @@ typeset -a selectedPackages=()
 for packageName in "${packageNames[@]}"
 do
     if askTo --subject "$packageName"; then
+	if [ "$SOMETHING_SPECIAL_DEFINITIONS" ] && specialInstallInstructions="$(setup-software --yes --select "$packageName" "$SOMETHING_SPECIAL_DEFINITIONS")"; then
+	    $DEBUGPREFIX eval "$specialInstallInstructions" || continue	# Don't try to update this package if its special install instructions have failed.
+	fi
+
 	selectedPackages+=("$packageName")
     elif [ "$isUpdatesAvailableSource" ]; then
 	# Check whether the user's reply was persistenly negative, and then
