somethingUpdatesInstall: Debugging: Adapt: Replace DEBUG switch statements with new shell-debugging toolset
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/somethingUpdatesInstall b/bin/somethingUpdatesInstall
--- a/bin/somethingUpdatesInstall
+++ b/bin/somethingUpdatesInstall
@@ -5,7 +5,6 @@ set -o pipefail
 : ${SOMETHING_AVAILABLE_VERSION_SEPARATOR:=[	 ]}
 
 readonly scriptName="$(basename -- "$0")"
-DEBUGPREFIX=; case ",${DEBUG:-}," in *,${scriptName},*) DEBUGPREFIX=verbose;; *,${scriptName}\!,*) DEBUGPREFIX=echotrace;; esac
 
 : ${SUDO:=sudoWithUnixhome}; [ $EUID -eq ${SOMETHING_UID:-0} ] && SUDO=''	# Need superuser rights for updating the ignore list.
 
@@ -16,7 +15,7 @@ Offers to update $SOMETHING_SUBJECT_NAME packages that are outdated, and memoriz
 choices for future runs. Exits with 99 if all packages are up-to-date.
 HELPTEXT
     echo
-    printf 'Usage: [DEBUG=%q] %s%q [--preserve-env=DEBUG] %s\n' "$scriptName" "${SUDO}${SUDO:+ }" "$(basename "$1")" '[-?|-h|--help]'
+    printf 'Usage: %s%q [--preserve-env=DEBUG] %s\n' "$scriptName" "${SUDO}${SUDO:+ }" "$(basename "$1")" '[-?|-h|--help]'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -133,7 +132,7 @@ checkUpdate()
 		    'Skip and try again next time')
 			;;
 		    'Try again now')
-			eval \$DEBUGPREFIX "${SOMETHING_UPDATE_COMMAND:?}" '"$packageName"' || status=$?;;
+			${DEBUG:+debugcommand  --for "$scriptName" --eval --} eval "${SOMETHING_UPDATE_COMMAND:?}" '"$packageName"' || status=$?;;
 		    'Ignore currently offered version')
 			ignoreVersion "$packageName";;
 		    'Ignore entered version pattern')
@@ -229,7 +228,7 @@ for packageName in "${packageNames[@]}"
 do
     if askTo --subject "$packageName"; then
 	if [ "$SOMETHING_SPECIAL_DEFINITIONS" ] && specialInstallCommandLine="$(setup-software --silence-no-definitions --yes --select "$packageName" "$SOMETHING_SPECIAL_DEFINITIONS")"; then
-	    $DEBUGPREFIX eval "$specialInstallCommandLine" || { status=$?; continue; }	# Don't try to update this package if its special install instructions have failed.
+	    ${DEBUG:+debugcommand  --for "$scriptName" --eval --} eval "$specialInstallCommandLine" || { status=$?; continue; }	# Don't try to update this package if its special install instructions have failed.
 	fi
 
 	selectedPackages+=("$packageName")
@@ -246,7 +245,7 @@ done
 
 [ ${#selectedPackages[@]} -eq 0 ] && exit 1
 
-eval \$DEBUGPREFIX "${SOMETHING_UPDATE_COMMAND:?}" '"${selectedPackages[@]}"' || status=$?
+${DEBUG:+debugcommand  --for "$scriptName" --eval --} eval "${SOMETHING_UPDATE_COMMAND:?}" '"${selectedPackages[@]}"' || status=$?
 
 [ "$SOMETHING_NO_CHECK_UPDATE" ] || checkUpdate
 
