versionCompare: Extract VERSION from additional text passed
This makes it easier to directly consume common version output (which often has the command's name prepended).

diff --git a/bin/versionCompare b/bin/versionCompare
--- a/bin/versionCompare
+++ b/bin/versionCompare
@@ -9,11 +9,20 @@ Compare the two passed VERSIONs, either returning 0 (equal), 1 (VERSION1
 larger), 2 (VERSION1 smaller), or the result of the passed compare operation.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'VERSION1 [-lt|-le|-eq|-ne|-ge|-gt] VERSION2 [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '...VERSION1... [-lt|-le|-eq|-ne|-ge|-gt] ...VERSION2... [-?|-h|--help]'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
+
+extractVersion()
+{
+    if [[ ! "$1" =~ [0-9]+(\.[0-9]+)* ]]; then
+	printf >&2 'ERROR: Not a version: %s\n' "$1"
+	exit 2
+    fi
+    printf %s "${BASH_REMATCH[0]}"
+}
 
 largerEqSmaller()
 {
@@ -42,14 +51,14 @@ largerEqSmaller()
 }
 
 if [ $# -eq 2 ]; then
-    version1="$1"; shift
-    version2="$1"; shift
+    version1="$(extractVersion "$1")"; shift
+    version2="$(extractVersion "$1")"; shift
     largerEqSmaller "$version1" "$version2"
     exit $?
 elif [ $# -eq 3 ]; then
-    version1="$1"; shift
+    version1="$(extractVersion "$1")"; shift
     compareOp="$1"; shift
-    version2="$1"; shift
+    version2="$(extractVersion "$1")"; shift
     largerEqSmaller "$version1" "$version2"
     case $? in
 	0)  [[ "$compareOp" = @(-eq|-le|-ge) ]];;
